import { createFileRoute } from '@tanstack/react-router'
import { LegalLayout } from '@/components/LegalLayout'

export const Route = createFileRoute('/terms')({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: 'Terms of Service — ScaleSage' },
      { name: 'description', content: 'The terms governing your engagement with ScaleSage.' },
    ],
  }),
})

function TermsPage() {
  return (
    <LegalLayout title="Terms of Service">
      <h2>1. Introduction</h2>
      <p>These Terms of Service ("Terms") govern the relationship between ScaleSage ("we", "us") and any business or individual ("you", "the Client") that engages our services. By signing a Service Agreement, making a payment, or using any of our services, you agree to these Terms.</p>

      <h2>2. Our Services</h2>
      <p>ScaleSage provides business system and automation services including: lead capture systems, customer follow-up automation, AI chat assistants, website builds, reputation management, database reactivation campaigns, business audits, AI readiness assessments, and custom automation builds. Specific scope is defined in the relevant Service Agreement. We do not provide legal, financial, or accounting advice. We do not guarantee specific business results — outcomes depend on factors outside our control including your market, pricing, and responsiveness.</p>

      <h2>3. Eligibility</h2>
      <p>You must be authorised to enter agreements on behalf of the business named in your Service Agreement. You must be at least 18 years of age.</p>

      <h2>4. Payment</h2>
      <ul>
        <li>Setup fees are payable in full before work begins.</li>
        <li>Monthly retainer fees are due on the same date each month following go-live.</li>
        <li>Database reactivation revenue share payments are due within 14 days of campaign report confirmation.</li>
        <li>All prices exclude VAT unless stated otherwise.</li>
        <li>Late payments (more than 7 days overdue) may result in pausing of services.</li>
        <li>Payments are processed via Stripe. We do not store card details.</li>
      </ul>

      <h2>5. Client Responsibilities</h2>
      <p>You agree to: provide all information, assets, and access required; respond to queries within agreed timeframes; ensure the accuracy and legality of all data you provide; respond to leads generated by our systems; maintain active subscriptions to required third-party platforms. We are not responsible for lost business resulting from your failure to respond to leads.</p>

      <h2>6. Intellectual Property</h2>
      <p>Upon full payment, all content, designs, automations, and configurations created specifically for you become your property. We retain the right to use anonymised examples for portfolio and marketing purposes unless you object in writing. You may not resell or white-label systems we build without prior written consent.</p>

      <h2>7. The 90-Day Guarantee</h2>
      <p>Where a 90-day performance guarantee is stated in your Service Agreement, the following conditions apply: (a) the guarantee applies only where you have completed the required onboarding steps; (b) the agreed success metric must be defined in writing before work begins; (c) if the metric is not achieved within 90 days, we will continue working at no extra charge until it is — or until both parties agree a revised metric. The guarantee does not apply where performance is impacted by your failure to respond to leads, provide required access, or maintain third-party platforms.</p>

      <h2>8. Limitation of Liability</h2>
      <p>Our total liability to you shall not exceed the total fees paid in the 3 months preceding the event giving rise to the claim. We are not liable for indirect, consequential, or special damages including lost revenue, business interruption, or loss of goodwill. Nothing excludes liability for death, personal injury, fraud, or any liability that cannot be excluded by law.</p>

      <h2>9. Confidentiality</h2>
      <p>Both parties agree to keep confidential any proprietary business information shared during the engagement. This survives termination for 2 years.</p>

      <h2>10. Data Protection</h2>
      <p>We handle all personal data in accordance with UK GDPR and the Data Protection Act 2018. See our Privacy Policy at <a href="/privacy">scalesage.ai/privacy</a>.</p>

      <h2>11. Acceptable Use</h2>
      <p>You agree not to use any system we build for unlawful, fraudulent, or harmful purposes, or to send spam or unsolicited bulk messages. We reserve the right to suspend services for violations.</p>

      <h2>12. Dispute Resolution</h2>
      <p>Disputes will first be addressed through good-faith negotiation. If unresolved within 30 days, either party may refer to mediation before litigation. This does not prevent either party from seeking urgent injunctive relief.</p>

      <h2>13. Governing Law</h2>
      <p>These Terms are governed by the laws of England and Wales. Disputes are subject to the exclusive jurisdiction of the courts of England and Wales.</p>

      <h2>14. Amendments</h2>
      <p>We may update these Terms with 30 days' notice to active clients. Continued use after the effective date constitutes acceptance.</p>

      <p style={{ marginTop: '2rem' }}><strong>Contact:</strong> <a href="mailto:midas@scalesage.ai">midas@scalesage.ai</a></p>
      <p style={{ fontStyle: 'italic', color: 'rgba(241,245,249,0.4)', marginTop: '2rem' }}>These Terms require review by a qualified solicitor before live use with clients.</p>
    </LegalLayout>
  )
}
